Задание 1

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('keywords.csv')
data[120:130]

               keyword    shows
120          дойки ком  1059292
121                аск  1045170
122            мой мир   993332
123              avito   984448
124  викинг фильм 2017   984999
125    школьный портал   982692
126    вк моя страница   979105
127       авито москва   979292
128        спортмастер   968154
129    новости украины   965720

In [3]:
geo_data = {

    'Центр':['москв', 'тул', 'ярославл'],

    'Северо-Запад': ['петербург', 'псков', 'мурманск'],

    'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']

}

In [4]:
n=0
data['region'] = 'undefined'
for line in data['keyword']:
    flag = False
    for key in list(geo_data.keys()):
        for city in geo_data[key]:
            if city in line:
                data['region'][n] = key
                flag = True
                break              
        if flag == True:
            break
    n += 1
    if n == 150:
        break
data[0:128]

/Users/ulyana/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

                                               keyword     shows     region
0                                                   вк  64292779  undefined
1                                        одноклассники  63810309  undefined
2                                                порно  41747114  undefined
3                                                 ютуб  39995567  undefined
4                                            вконтакте  21014195  undefined
5                           одноклассники моя страница  19976138  undefined
6                                                 майл  15144673  undefined
7                                                авито  14786593  undefined
8                                           переводчик  14453469  undefined
9                                               яндекс  13344734  undefined
10                                     сбербанк онлайн  10725673  undefined
11                                                mail   7687204  undefined
12                                                игры   6075762  undefined
13                                             youtube   5729958  undefined
14                              вконтакте моя страница   5971451  undefined
15                                                секс   5431732  undefined
16                                                гугл   5175471  undefined
17                                                  dr   4880955  undefined
18                                         алиэкспресс   4879645  undefined
19                                             рамблер   4540421  undefined
20                                         фильмы 2016   4486635  undefined
21                                              погода   4344510  undefined
22                                                  vk   4330448  undefined
23                                   ютуб видеохостинг   4215267  undefined
24                                               дойки   4133424  undefined
25                       одноклассники социальная сеть   4018230  undefined
26                                            мультики   3866664  undefined
27                                             контакт   3815111  undefined
28                                             фейсбук   3669993  undefined
29                                         порно видео   3858938  undefined
..                                                 ...       ...        ...
98                                  мтс личный кабинет   1766893  undefined
99                            скачать музыку бесплатно   1415741  undefined
100                                  программа передач   1302601  undefined
101                           телепрограмма на сегодня   1318857  undefined
102                                          тв онлайн   1610178  undefined
103                                              gmail   1280529  undefined
104       в контакте моя страница вход на мою страницу   1267689  undefined
105                                    гугл переводчик   2014530  undefined
106                                           гисметео   1259766  undefined
107                                        мультфильмы   1251931  undefined
108                                            м видео   1229519  undefined
109                                      телепрограмма   1224238  undefined
110                                                пгу   1220294  undefined
111                                         фотострана   1153162  undefined
112                                          чемпионат   1151235  undefined
113  смотреть фильмы онлайн в хорошем качестве бесп...   1138927  undefined
114                                               кино   1115188  undefined
115                                         барбоскины   1114840  undefined
116              фильмы 2016 смотреть хорошем качестве   1109701  undefined
117                             алиэкспресс на русском   1090214  undefined
118                                   odnoklassniki ru   1076481  undefined
119                                         майл почта   3386214  undefined
120                                          дойки ком   1059292  undefined
121                                                аск   1045170  undefined
122                                            мой мир    993332  undefined
123                                              avito    984448  undefined
124                                  викинг фильм 2017    984999  undefined
125                                    школьный портал    982692  undefined
126                                    вк моя страница    979105  undefined
127                                       авито москва    979292      Центр

[128 rows x 3 columns]

Задание 2

In [7]:
def movie_classifier():
    
    n = 0
    ratings['class'] = 'undefined'
    for rating in ratings['rating']:
        if rating <= 2.0:
            ratings['class'][n] = 'низкий рейтинг'
        if 2.0 < rating <= 4.0:
            ratings['class'][n] = 'средний рейтинг'
        if rating >= 4.5:
            ratings['class'][n] = 'высокий рейтинг'
        n += 1
        if n == 500:
            break

In [8]:
ratings = pd.read_csv('ratings.csv')

In [9]:
ratings.head()

   userId  movieId  rating     timestamp
0       1      2.0     3.5  1.112486e+09
1       1     29.0     3.5  1.112485e+09
2       1     32.0     3.5  1.112485e+09
3       1     47.0     3.5  1.112485e+09
4       1     50.0     3.5  1.112485e+09

In [10]:
movie_classifier()

/Users/ulyana/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/Users/ulyana/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()
/Users/ulyana/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

In [11]:
ratings[100:200]

     userId  movieId  rating     timestamp            class
100       1   3037.0     3.5  1.112486e+09  средний рейтинг
101       1   3081.0     4.0  1.094786e+09  средний рейтинг
102       1   3153.0     4.0  1.112486e+09  средний рейтинг
103       1   3265.0     3.5  1.112485e+09  средний рейтинг
104       1   3438.0     3.5  1.112486e+09  средний рейтинг
105       1   3476.0     3.5  1.094786e+09  средний рейтинг
106       1   3479.0     4.0  1.112486e+09  средний рейтинг
107       1   3489.0     4.0  1.112486e+09  средний рейтинг
108       1   3499.0     4.0  1.112485e+09  средний рейтинг
109       1   3889.0     4.0  1.112486e+09  средний рейтинг
110       1   3932.0     3.0  1.094786e+09  средний рейтинг
111       1   3996.0     4.0  1.094786e+09  средний рейтинг
112       1   3997.0     3.5  1.112486e+09  средний рейтинг
113       1   4011.0     4.0  1.112485e+09  средний рейтинг
114       1   4027.0     4.0  1.112485e+09  средний рейтинг
115       1   4105.0     3.5  1.094786e+09  средний рейтинг
116       1   4128.0     4.0  1.112485e+09  средний рейтинг
117       1   4133.0     3.0  1.112486e+09  средний рейтинг
118       1   4226.0     3.5  1.112484e+09  средний рейтинг
119       1   4306.0     4.0  1.094786e+09  средний рейтинг
120       1   4446.0     3.5  1.112486e+09  средний рейтинг
121       1   4467.0     4.0  1.112486e+09  средний рейтинг
122       1   4571.0     4.0  1.112486e+09  средний рейтинг
123       1   4720.0     3.5  1.094786e+09  средний рейтинг
124       1   4754.0     4.0  1.112485e+09  средний рейтинг
125       1   4878.0     3.5  1.112485e+09  средний рейтинг
126       1   4896.0     4.0  1.112486e+09  средний рейтинг
127       1   4911.0     4.0  1.112486e+09  средний рейтинг
128       1   4915.0     3.0  1.112486e+09  средний рейтинг
129       1   4941.0     3.5  1.112486e+09  средний рейтинг
..      ...      ...     ...           ...              ...
170       1   8507.0     5.0  1.094786e+09  высокий рейтинг
171       1   8636.0     4.5  1.112485e+09  высокий рейтинг
172       1   8690.0     3.5  1.112485e+09  средний рейтинг
173       1   8961.0     4.0  1.112486e+09  средний рейтинг
174       1  31696.0     4.0  1.112486e+09  средний рейтинг
175       2      3.0     4.0  9.748209e+08  средний рейтинг
176       2     62.0     5.0  9.748206e+08  высокий рейтинг
177       2     70.0     5.0  9.748207e+08  высокий рейтинг
178       2    110.0     4.0  9.748207e+08  средний рейтинг
179       2    242.0     3.0  9.748208e+08  средний рейтинг
180       2    260.0     5.0  9.748210e+08  высокий рейтинг
181       2    266.0     5.0  9.748207e+08  высокий рейтинг
182       2    469.0     3.0  9.748206e+08  средний рейтинг
183       2    480.0     5.0  9.748207e+08  высокий рейтинг
184       2    541.0     5.0  9.748210e+08  высокий рейтинг
185       2    589.0     5.0  9.748207e+08  высокий рейтинг
186       2    891.0     2.0  9.748210e+08   низкий рейтинг
187       2    908.0     4.0  9.748207e+08  средний рейтинг
188       2    924.0     5.0  9.748210e+08  высокий рейтинг
189       2   1121.0     3.0  9.748206e+08  средний рейтинг
190       2   1196.0     5.0  9.748210e+08  высокий рейтинг
191       2   1210.0     5.0  9.748206e+08  высокий рейтинг
192       2   1214.0     5.0  9.748210e+08  высокий рейтинг
193       2   1249.0     5.0  9.748207e+08  высокий рейтинг
194       2   1259.0     5.0  9.748207e+08  высокий рейтинг
195       2   1270.0     5.0  9.748210e+08  высокий рейтинг
196       2   1327.0     5.0  9.748208e+08  высокий рейтинг
197       2   1356.0     5.0  9.748206e+08  высокий рейтинг
198       2   1544.0     5.0  9.748209e+08  высокий рейтинг
199       2   1580.0     4.0  9.748207e+08  средний рейтинг

[100 rows x 5 columns]

Задание 3

In [12]:
user_data = ratings.groupby('userId').count()
user_data.head()

        movieId  rating  timestamp  class
userId
1           175     175        175    175
2            61      61         61     61
3           187     187        187    187
4            28      28         28     28
5            66      66         66     66

In [13]:
user_data = user_data[ user_data['class'] >= 100 ]
user_data.head()

        movieId  rating  timestamp  class
userId
1           175     175        175    175
3           187     187        187    187
7           276     276        276    276
11          504     504        504    504
14          243     243        243    243

In [15]:
timestamp_data = ratings.groupby('userId').agg(['min', 'max'])['timestamp'].head()

In [16]:
user_data_final = user_data.merge(timestamp_data, left_index=True, right_index=True)

In [17]:
user_data_final

        movieId  rating  timestamp  class           min           max
userId
1           175     175        175    175  1.094786e+09  1.112486e+09
3           187     187        187    187  9.448971e+08  9.451761e+08

Задание 4

In [18]:
years=list(range(1950,2011))

In [19]:
movies = pd.read_csv('movies.csv')
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [22]:
def production_year(line):
    n=0
    movies['year'] = '1900'
    for line in movies['title']:
        for year in years:
            if str(year) in line:
                movies['year'][n] = year
                break
        n += 1

In [34]:
def production_year(title):
    for year in years:
        if str(year) in title:
            return year
            return '1900'

In [35]:
movies['year']=movies.title.apply(production_year)

In [38]:
movies_and_ratings = movies.merge(ratings, left_index=True, right_index=True)
movies_and_ratings.head()

,movieId_x,title,genres,year,userId,movieId_y,rating,timestamp,class
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1995.0,1,2.0,3.5,1.112486e+09,средний рейтинг
1,2,Jumanji (1995),Adventure|Children|Fantasy,1995.0,1,29.0,3.5,1.112485e+09,средний рейтинг
2,3,Grumpier Old Men (1995),Comedy|Romance,1995.0,1,32.0,3.5,1.112485e+09,средний рейтинг
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,1995.0,1,47.0,3.5,1.112485e+09,средний рейтинг
4,5,Father of the Bride Part II (1995),Comedy,1995.0,1,50.0,3.5,1.112485e+09,средний рейтинг

In [40]:
movies_and_ratings.groupby('year').rating.mean().sort_values(ascending=False)

year
1994.0    3.796984
1958.0    3.780822
1993.0    3.715633
1988.0    3.699074
1987.0    3.697452
1989.0    3.674194
1972.0    3.673516
1965.0    3.659639
1970.0    3.656863
1996.0    3.645383
1995.0    3.644515
1952.0    3.618321
1990.0    3.611465
1974.0    3.609694
1961.0    3.605691
1962.0    3.592715
1969.0    3.592697
1992.0    3.589820
1977.0    3.588384
1967.0    3.582857
1973.0    3.578199
1983.0    3.578125
1971.0    3.577670
1984.0    3.574786
1991.0    3.565495
1985.0    3.564961
1997.0    3.563447
1986.0    3.562030
1957.0    3.555215
2003.0    3.554198
            ...
1963.0    3.550676
1953.0    3.547794
2002.0    3.547267
1978.0    3.541667
1998.0    3.537838
1981.0    3.528112
1979.0    3.514925
1968.0    3.485294
1959.0    3.476821
2005.0    3.475676
1950.0    3.475610
1955.0    3.472603
1976.0    3.472362
1975.0    3.469543
1956.0    3.459559
1964.0    3.453757
1982.0    3.449580
1980.0    3.422131
2000.0    3.421697
1966.0    3.417085
1999.0    3.394834
1954.0    3.393805
2010.0    3.393451
2004.0    3.389518
1951.0    3.364000
1960.0    3.324324
2006.0    3.268692
2009.0    3.200901
2007.0    3.168514
2008.0    3.146217
Name: rating, Length: 61, dtype: float64